package eu.gloria.rti;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-01-22T13:26:41.122+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "gloria_rti", 
                  wsdlLocation = "http://localhost:8080/RTI/services/gloria_rtiSOAP?wsdl",
                  targetNamespace = "http://gloria.eu/rti") 
public class GloriaRti_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gloria.eu/rti", "gloria_rti");
    public final static QName GloriaRtiSOAP = new QName("http://gloria.eu/rti", "gloria_rtiSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RTI/services/gloria_rtiSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GloriaRti_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/RTI/services/gloria_rtiSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GloriaRti_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GloriaRti_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GloriaRti_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GloriaRti
     */
    @WebEndpoint(name = "gloria_rtiSOAP")
    public GloriaRti getGloriaRtiSOAP() {
        return super.getPort(GloriaRtiSOAP, GloriaRti.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GloriaRti
     */
    @WebEndpoint(name = "gloria_rtiSOAP")
    public GloriaRti getGloriaRtiSOAP(WebServiceFeature... features) {
        return super.getPort(GloriaRtiSOAP, GloriaRti.class, features);
    }

}
